#!/usr/bin/env python3
#
# https://icalendar.readthedocs.io/en/latest/usage.html#example

# TODO: Parse all cinemas, then parse film info to put into the description.

import datetime
import logging
import re
import time

import click
import icalendar
import json
import pytz
import requests
import slugify
import yaml

from bs4 import BeautifulSoup
from lxml import etree
from rich.logging import RichHandler
from rich.progress import track


re_runtime = re.compile(r"^(?P<hours>\d+)\s*hrs?\s+(?P<minutes>\d+)mins?$")
re_start_time = re.compile(r"^(?P<hour>\d+):(?P<minutes>\d\d)\s+(?P<period>AM|PM)$")
re_duration = re.compile(r"^PT(?P<minutes>\d+)M$")
re_duration_new = re.compile(r"^(?:(?P<hours>\d+)h)?\s*(?:(?P<minutes>\d+)m)?$")


class ImdbICS:
    PADDING = 25  # minutes
    START = datetime.date.today()
    DAYS = 16

    VENUES = [
        {
            "name": "Regal Bella Bottega, Redmond",
            "id": "ci0001864",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Grand Illusion Cinema, Seattle",
            "id": "ci0005472",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "The Beacon, Seattle",
            "id": "ci1024213",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "iPic Theaters at Redmond Town Center, Redmond",
            "id": "ci0014968",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "AMC Pacific Place 11, Seattle",
            "id": "ci0006735",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "AMC Pacific Place 12, Woodinville",
            "id": "ci0004663",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "SIFF Cinema Uptown, Seattle",
            "id": "ci16639653",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "SIFF Cinema Egyptian, Seattle",
            "id": "ci60177107",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "SIFF Film Center, Seattle",
            "id": "ci16639652",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "SIFF Cinema Downtown, Seattle",
            "id": "ci5397678",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Cinemark Lincoln Square, Bellevue",
            "id": "ci0014104",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Cinemark Reserve Lincoln Square, Bellevue",
            "id": "ci100961247",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Cinemark Totem Lake, Kirkland",
            "id": "ci1025162",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Central Cinema, Seattle",
            "id": "ci0015312",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Ark Lodge Cinemas, Seattle",
            "id": "ci0034743",
            "timezone": "America/Los_Angeles",
        },
        {
            "name": "Landmark Crest Cinema, Shoreline",
            "id": "ci0001936",
            "timezone": "America/Los_Angeles",
        },
    ]

    def __init__(self):
        self.session = requests.Session()
        self.title_info = {}  # str → dict

    def main(self):
        logging.info(f"Getting info from {len(self.VENUES)} venues")

        for venue in self.VENUES:
            ics = self.get_ics(venue)

            with open(f"ics/{venue['id']}.ics", "w") as f:
                f.write(ics)

        # Write venue metadata
        with open(f"_data/venues.yaml", "w") as f:
            f.write(yaml.dump(sorted(self.VENUES, key=lambda x: x["name"])))

    def get_soup(self, url, attempts=3):
        while True:
            r = self.session.get(
                url,
                headers={
                    "User-Agent": "custom",
                    "Accept-Language": "en-US,en;q=0.9,it;q=0.8",
                },
            )

            if r.status_code == 200:
                break

            if attempts == 1:
                logging.warning(f"Out of HTTP attempts for this URL; raising error")
                r.raise_for_status()

            logging.warning(f"Did not get HTTP 200; will re-attempt after sleep")
            attempts -= 1
            time.sleep(3)

        with open("/tmp/imdb-ics.html", "wb") as f:
            f.write(r.content)

        return BeautifulSoup(r.content, "html.parser")

    def text(self, soup, pattern):
        return soup.select(pattern)[0].text.strip()

    def attr(self, soup, pattern, attr):
        return soup.select(pattern)[0][attr].strip()

    def parse_duration(self, val):
        m = re_duration.match(val)
        if m is not None:
            return int(m.group("minutes"))

        m = re_duration_new.match(val)

        return (int(m.group("hours") or 0) * 60) + int(m.group("minutes") or 0)

    def populate_title_info(self, imdb_title_id):
        try:
            return self.title_info[imdb_title_id]
        except KeyError:
            pass

        logging.info(f"Getting info for IMDB title '{imdb_title_id}'")

        url = f"https://www.imdb.com/title/{imdb_title_id}/"

        root = self.get_soup(url)
        raw = root.select_one('script[type="application/ld+json"]').text

        data = json.loads(raw)
        logging.debug(f"Downloaded info for '{data['name']}'")

        self.title_info[imdb_title_id] = data

        return self.title_info[imdb_title_id]

    def get_ics(self, venue):
        base_url = f"https://www.imdb.com/showtimes/cinema/US/{venue['id']}"
        logging.info(f"Getting info for '{venue['name']}'")

        strip_suffixes = (
            " ({})".format(datetime.date.today().year),
            " ({})".format(datetime.date.today().year - 1),
        )

        soup = self.get_soup(base_url)

        try:
            venue["address"] = self.text(soup, ".ipc-page-section span")
        except IndexError:
            address_parts = []
            for x in soup.select("div.description span"):
                part = x.text.strip()
                if part == "|":
                    # After we hit a "|" it will just be a phone number
                    break
                address_parts.append(part)
            venue["address"] = ", ".join(address_parts)

        logging.debug(f"Found info for '{venue['name']}' ({venue['address']})")

        assert venue["address"]

        cal = icalendar.Calendar()
        cal.add("prodid", "-//icalendar//mxm.dk//")
        cal.add("version", "2.0")
        cal.add("name", venue["name"])
        cal.add("x-wr-calname", venue["name"])
        cal.add("last-modified", datetime.datetime.now(datetime.UTC))

        num_events_venue = 0
        for idx in range(self.DAYS):
            date = self.START + datetime.timedelta(days=idx)
            logging.info(f"Getting showtimes for '{venue['name']}' on {date}")

            soup = self.get_soup(
                "{}/{:04d}-{:02d}-{:02d}".format(
                    base_url,
                    date.year,
                    date.month,
                    date.day,
                )
            )

            num_events_date = 0
            for elem in soup.select(
                ".list.detail .list_item, .ipc-metadata-list .ipc-metadata-list-summary-item"
            ):
                title = self.text(elem, ".info h3, h3.ipc-title__text")

                for needle in strip_suffixes:
                    if title.endswith(needle):
                        title = title[: -len(needle)]

                try:
                    href = self.attr(
                        elem, ".info h3 a, a.ipc-title-link-wrapper", "href"
                    )
                except IndexError:
                    # Some films are not on IMDB.
                    continue

                imdb_title_id = f"{href}/".split("/")[3].split("?", 1)[0]

                self.populate_title_info(imdb_title_id)

                try:
                    runtime = self.parse_duration(
                        self.attr(elem, "time[itemprop=duration]", "datetime")
                    )
                except IndexError:
                    try:
                        runtime = self.parse_duration(
                            self.text(
                                elem,
                                "div.li-title-metadata > span.li-title-metadata-item:nth-child(2)",
                            )
                        )
                    except IndexError:
                        runtime = 120

                try:
                    first_button = elem.select("a.ipc-btn")[0]
                except IndexError:
                    groups = elem.select("h5.li_group")
                else:
                    groups = first_button.parent.parent.parent.find_all(recursive=False)

                for group in groups:
                    try:
                        suffix = (
                            self.text(group, "div:nth-child(1)")
                            .strip("():")
                            .replace("Standard", "")
                        )

                        showtimes = []

                        for x in group.select("div:nth-child(2) a"):
                            showtimes.append(self.parse_showtime(x.text))

                    except IndexError:
                        suffix = group.text.replace("Showtimes", "").strip().rstrip(":")

                        showtimes = self.parse_showtimes(group.findNext("div").text)

                    if suffix:
                        suffix = f" ({suffix})"

                    for hour, minute in showtimes:
                        event = icalendar.Event()

                        uid = (
                            venue["id"],
                            imdb_title_id,
                            slugify.slugify(suffix),
                            date.year,
                            date.month,
                            date.day,
                            hour,
                            minute,
                        )

                        # Overview
                        event.add("uid", "-".join(str(x) for x in uid))
                        event.add("summary", f"{title}{suffix}")
                        event.add(
                            "location", "{}, {}".format(venue["name"], venue["address"])
                        )

                        # Calculate times
                        start = datetime.datetime(
                            year=date.year,
                            month=date.month,
                            day=date.day,
                            hour=hour,
                            minute=minute,
                            tzinfo=pytz.timezone(venue["timezone"]),
                        )

                        estimated_start = start + datetime.timedelta(
                            minutes=self.PADDING,
                        )
                        end = estimated_start + datetime.timedelta(
                            minutes=self.round_to_nearest(runtime, 5),
                        )
                        event.add("dtstamp", start)
                        event.add("dtstart", start)
                        event.add("dtend", end)

                        # Description
                        data = self.title_info[imdb_title_id]
                        description = []
                        hours, minutes = divmod(runtime, 60)
                        description.append(
                            f"Duration: {hours}h {minutes:02d}m ({runtime} mins)"
                        )
                        try:
                            description.append(
                                data["description"].replace("&apos;", "'")
                            )
                        except KeyError:
                            pass
                        description.append(data["url"])
                        description.append(
                            f"Estimated start: {estimated_start.hour}:{estimated_start.minute:02d}"
                        )
                        estimated_start
                        try:
                            description.append(
                                f"IMDb rating: {data['aggregateRating']['ratingValue']}"
                            )
                        except KeyError:
                            pass
                        description.append(data["url"])

                        event.add("description", "\n\n".join(description))

                        cal.add_component(event)

                        num_events_date += 1
                        num_events_venue += 1

            logging.debug(
                f"Found {num_events_date} events for {venue['name']} on {date}"
            )

            if num_events_date == 0 and venue["id"] == "ci0001864":
                raise click.ClickException(
                    "No events for local cinema; exiting. Debug in /tmp"
                )

        fn = logging.warning if num_events_venue == 0 else logging.debug
        fn(f"Found {num_events_venue} total events for {venue['name']}")

        return cal.to_ical().decode("utf-8")

    def round_to_nearest(self, val, nearest_to):
        return (val + (nearest_to - 1)) // nearest_to * nearest_to

    def parse_showtimes(self, val):
        val = val.replace("Get Tickets", "")

        hour_offset = 0

        for x in val.split("|"):
            x = x.strip()

            if x.endswith("pm"):
                hour_offset = 12

            hour, minute = [int(y) for y in x.split(" ", 1)[0].split(":", 1)]

            if hour_offset == 0 and hour == 12:
                hour = 0

            if hour < 12:
                hour += hour_offset

            yield hour, minute

    def parse_showtime(self, val):
        split = re.split(r"[:\s]", val)

        hour = int(split[0])
        minute = int(split[1])

        hour_offset = 12 if split[2] == "PM" else 0
        if hour_offset == 0 and hour == 12:
            hour = 0
        if hour < 12:
            hour += hour_offset

        return hour, minute


@click.command()
@click.option("--verbose", is_flag=True, default=False, help="Verbose.")
def main(verbose):
    level = logging.DEBUG if verbose else logging.INFO

    logging.basicConfig(
        level=level, format="%(message)s", datefmt="[%X]", handlers=[RichHandler()]
    )

    ImdbICS().main()


if __name__ == "__main__":
    main()
